#!/usr/bin/env python3
"""Order the study sets: a trimmed emotion starter, then the book, then the curriculum.

The 58 `set::emotions` words were generated by a model for the semantic field, so the
set carries three faults that a hand-picked list would not:

  * 意识 is not an emotion at all -- "consciousness; awareness" -- and it is the
    commonest word in the set, so it sat at the very front. It loses both tags and
    rejoins the curriculum as the ordinary HSK word it is.
  * FOUR near-synonym clusters, 14 words competing. Teaching semantically-related words
    in one block is a known way to slow acquisition: the items interfere and you end up
    unsure which is which. One word per cluster stays; the rest wait until it is solid.
  * Seven below Zipf 3.0 -- 亢奋, 忐忑, 怅然, 惶恐, 憋屈, 焦灼, 释然. Too rare to hold.

Deferring means losing `liked`, never losing `set::emotions`. The label is identity; the
order comes from a separate tag. So the set stays addressable and one command restores it.

Stella An is deferred the same way: `next::stella-an` becomes `set::stella-an`. It scored
0.1 tokens per card against 《十年》 -- it is essay vocabulary, not fiction vocabulary, and
it is worth pulling forward only when the reading changes.

Usage: bash freq_data/anki_op.sh order-sets freq_data/order_study_sets.py --apply
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path("/home/vincent/anki-headless")
sys.path.insert(0, str(ROOT))

import anki.collection  # noqa: E402,F401
from anki.collection import Collection  # noqa: E402

NOT_AN_EMOTION = {"意识"}
#: Keep the commonest of each; the others wait. Chosen by wordfreq, not by feel.
CLUSTERS = [("焦虑", "焦躁", "烦躁", "焦灼"), ("惭愧", "羞愧", "愧疚", "内疚"),
            ("悲伤", "悲哀", "心酸", "忧郁"), ("惊讶", "诧异", "震惊")]
RARE_FLOOR = 3.0


def strip_html(s):
    return re.sub(r"<[^>]+>", "", s or "").replace("&nbsp;", " ").strip()


def main():
    from wordfreq import zipf_frequency
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=str(ROOT / "collection.anki2"))
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    col = Collection(args.db)
    try:
        emo = {}
        for nid in col.find_notes("tag:set::emotions"):
            emo[strip_html(col.get_note(nid).fields[0])] = nid

        keep_cluster, drop_cluster = set(), set()
        for cl in CLUSTERS:
            have = sorted((w for w in cl if w in emo),
                          key=lambda w: -zipf_frequency(w, "zh"))
            if have:
                keep_cluster.add(have[0])
                drop_cluster.update(have[1:])
        rare = {w for w in emo if zipf_frequency(w, "zh") < RARE_FLOOR}
        front = sorted(set(emo) - NOT_AN_EMOTION - drop_cluster - (rare - keep_cluster))
        defer = sorted(set(emo) - set(front) - NOT_AN_EMOTION)

        print(f"emotions: {len(emo)}")
        print(f"  FRONT ({len(front)}, keep `liked`): {' '.join(front)}")
        print(f"  DEFER ({len(defer)}, lose `liked`): {' '.join(defer)}")
        print(f"  DROPPED FROM THE SET ({len(NOT_AN_EMOTION)}): {' '.join(NOT_AN_EMOTION)}")

        stella = col.find_notes("tag:next::stella-an")
        print(f"\nstella an: {len(stella)} notes  next::stella-an -> set::stella-an (defer)")
        if not args.apply:
            print("\n(dry run; nothing written)")
            return

        for word, nid in emo.items():
            note = col.get_note(nid)
            if word in NOT_AN_EMOTION:
                note.remove_tag("set::emotions")
                note.remove_tag("liked")
            elif word in front:
                if "liked" not in note.tags:
                    note.add_tag("liked")
            else:
                note.remove_tag("liked")
            col.update_note(note)

        for nid in stella:
            note = col.get_note(nid)
            note.remove_tag("next::stella-an")
            if "set::stella-an" not in note.tags:
                note.add_tag("set::stella-an")
            col.update_note(note)

        print(f"\nverify: tag:liked notes {len(col.find_notes('tag:liked'))} (want {len(front)})")
        print(f"verify: set::emotions {len(col.find_notes('tag:set::emotions'))} "
              f"(want {len(emo) - len(NOT_AN_EMOTION)})")
        print(f"verify: 意识 still liked: {len(col.find_notes('意识 tag:liked'))} (want 0)")
        print(f"verify: next::stella-an {len(col.find_notes('tag:next::stella-an'))} (want 0)")
        print(f"verify: set::stella-an {len(col.find_notes('tag:set::stella-an'))} (want {len(stella)})")
        print(f"verify: book::十年 untouched {len(col.find_notes('tag:book::十年'))}")
    finally:
        col.close()


if __name__ == "__main__":
    main()
